Demo page for Litle (Vantiv) Plugin
killbill/killbill-litle-demo pull request #1
Opened 2016-11-29 19:19 UTC by javier-gomez-github

2016-11-29 21:57 UTC, pierre reviewed
Awesome! Just a couple of questions and remarks.

2016-11-29 21:57 UTC, pierre commented on Gemfile.lock
> +GEM
Nit: I don't think you need to check this file in (see https://github.com/killbill/killbill-stripe-demo/blob/master/.gitignore#L2).

2016-11-29 21:57 UTC, pierre commented on app.rb
> +    # sometime returns an error: "Error locking accountRecordId='***'"
This is odd / should never happen. Do you have more details?

2016-11-29 21:57 UTC, pierre commented on app.rb
> +                <td>Paypage ID</td><td><input type="text" id="request$paypageId" name="request$paypageId" value="a2y4o6m8k0" disabled/></td>
This should be configurable as it depends on the merchant - maybe introduce an environment variable like `KB_URL` (and update the README)?

2016-11-30 12:40 UTC, javier-gomez-github-zz commented on app.rb
> +    # sometime returns an error: "Error locking accountRecordId='***'"
Yes, this is not necessary. I based my code in the dwolla-demo and forgot to remove this line.

2016-11-30 12:41 UTC, javier-gomez-github commented on app.rb
> +                <td>Paypage ID</td><td><input type="text" id="request$paypageId" name="request$paypageId" value="a2y4o6m8k0" disabled/></td>
Yes! I wanted you to confirm this before proceeding. I'll add the environment variables and update the README. Thanks @pierre

2016-11-30 13:58 UTC, javier-gomez-github commented
@pierre 
Done with fixes! 💪

2016-11-30 14:23 UTC, pierre requested changes

2016-11-30 14:23 UTC, pierre commented on app.rb
> -    subscription.create(user, reason, comment, nil, true, options)
You still need to create the subscription!

2016-11-30 14:23 UTC, pierre commented on app.rb
> +            value=<%= "'#{@customerId}'" %>
Extra debug statement?

2016-11-30 14:32 UTC, javier-gomez-github commented
@pierre my bad, the christmas spirit 🎅  made me add and delete extra lines 😰

2016-11-30 15:20 UTC, merged

2016-11-30 15:20 UTC, pierre commented
Thanks!